INSERT INTO {{ params.psql_prd_table }} (
    trip_id,
    taxi_id,
    trip_start_timestamp,
    trip_start_date_id,
    trip_start_time,
    trip_end_timestamp,
    trip_end_date_id,
    trip_end_time,
    trip_seconds,
    trip_miles,
    pickup_census_tract,
    dropoff_census_tract,
    pickup_community_area,
    dropoff_community_area,
    fare,
    tips,
    tolls,
    extras,
    trip_total,
    payment_type,
    company,
    pickup_centroid_latitude,
    pickup_centroid_longitude,
    pickup_centroid_location,
    dropoff_centroid_latitude,
    dropoff_centroid_longitude,
    dropoff_centroid_location)
    SELECT  trip_id,
            taxi_id,
            trip_start_timestamp,
            TO_CHAR(trip_start_timestamp, 'yyyymmdd')::INT as trip_start_date_id,
            trip_start_timestamp::TIME as trip_start_time,
            trip_end_timestamp,
            TO_CHAR(trip_start_timestamp, 'yyyymmdd')::INT as trip_end_date_id,
            trip_end_timestamp::TIME as trip_end_time,
            trip_seconds,
            trip_miles,
            pickup_census_tract,
            dropoff_census_tract,
            pickup_community_area,
            dropoff_community_area,
            fare,
            tips,
            tolls,
            extras,
            trip_total,
            payment_type,
            company,
            pickup_centroid_latitude,
            pickup_centroid_longitude,
            pickup_centroid_location,
            dropoff_centroid_latitude,
            dropoff_centroid_longitude,
            dropoff_centroid_location
    FROM {{ params.psql_staging_table }}
    ON CONFLICT (trip_id) DO NOTHING;

DROP TABLE {{ params.psql_staging_table }};