
CREATE TABLE IF NOT EXISTS trip_data_staging(
    trip_id TEXT PRIMARY KEY,
    taxi_id TEXT,
    trip_start_timestamp TIMESTAMP,
    trip_end_timestamp TIMESTAMP,
    trip_seconds INT,
    trip_miles FLOAT(2),
    pickup_census_tract TEXT,
    dropoff_census_tract TEXT,
    pickup_community_area SMALLINT,
    dropoff_community_area SMALLINT,
    fare FLOAT(2),
    tips FLOAT(2),
    tolls FLOAT(2),
    extras FLOAT(2),
    trip_total FLOAT(2),
    payment_type TEXT,
    company TEXT,
    pickup_centroid_latitude FLOAT(9),
    pickup_centroid_longitude FLOAT(9),
    pickup_centroid_location POINT,
    dropoff_centroid_latitude FLOAT(9),
    dropoff_centroid_longitude FLOAT(9),
    dropoff_centroid_location POINT
)